= Changelog

All notable changes to this project will be documented in this file.

The format is based on https://keepachangelog.com/en/1.0.0/[Keep a Changelog],
and this project adheres to https://semver.org/spec/v2.0.0.html[Semantic Versioning].

== [Unreleased] 
// 2.0.0
=== Added 
* https://gohugo.io/content-management/multilingual/[Multilingual mode] support. 
Thus, the `i18n` folder is now added. 
For now, the translation is only available for English (US) and Tagalog. 
If you know some language that is not listed in the folder, feel free to contribute translating to other languages. 
* Add quick taxonomy search list. 
The feature was inspired from https://www.ii.com/[this site]. 
* Add a CDN-less MathJax usage option as `params.useLocalMathjax`. 
(Only works for MathJax v3.)
* Add custom messages for the 404 page. 
Thus, the following site custom parameters has been added:
** `params.notFoundHeader`
** `params.notFoundLinkMessage`
** `params.notFoundMessage` 
* Add a custom message option for the search widget label by `params.searchLabel`. 
* Add content headers (similar to 
https://en.wikibooks.org/wiki/LaTeX/Counters[LaTeX counters]) with the 
`params.useContentCounters` option. 
* Add a reader mode for your content with `params.enableContentReaderMode`. 
* Add a compact list mode for the homepage post list with `params.enableCompactListMode`. 
* Add a "Back to top" button on the footer with `params.enableBackToTopLink`. 
* Add JSON+LD schema. 
It is disabled by default so you have to manually switch the `params.enableJsonld` first. 
* Add a image zoom feature (using 
https://github.com/francoischalifour/medium-zoom[medium-zoom library]) that can be 
switched with `params.enableContentImageZoom`. 
You can also set the background color with `params.setContentImageZoomBackground`. 

=== Changed 
* **IMPORTANT**: Rename the theme from "Terminal Plus-Minus" to "Arch Terminal". 
* **IMPORTANT**: Content pagination is now disabled by default. 
In effect, an additional site config option `params.enableContentPagination` has 
been added. 
* **BREAKING CHANGE**: Update the layout code for the 
https://github.com/gohugoio/hugo/releases/tag/v0.58.0[breaking changes at Hugo v0.58.0]. 
__Thus, the theme now requires Hugo v0.58.0.__ 
* **BREAKING CHANGE**: Change `params.enableSyntaxHighlighting` to 
`params.enableLazySyntaxHighlighting`. 
* **BREAKING CHANGE**: Remove `params.setMathjaxToV3` to be replaced with 
`params.setMathjaxToV2` since the theme will now use MathJax v3 by default. 
* Revise MathJax support (again) with the v2 replaced to v3 as the 
default MathJax version since MathJax v3 got the official production release. 
* Update the stylesheet to consider consistent and pleasant typography. 
One of the biggest change is the consideration of 
https://zellwk.com/blog/why-vertical-rhythms/[vertical rhythms] and the absence of 
the custom styles. 

=== Fixed
* Update the SCSS load order to make the automatic second theming work. 
(I forgot that SCSS variables are imperative, not declarative.)
* Make the external scripts to run asynchronously to prevent DOM blocking and 
improve the performance of the site. 




== [1.4.0] - 2019-09-05
=== Added 
* Add a theme toggle switch (or dark mode toggle switch or whatever). 
Thus, additional variables in the default stylesheet config has been added. 
Please take a look at the link:../assets/scss/default.scss[default config] to 
see the added variables. 
* The toggle switch is disabled by default so the `params.enableThemeToggle` is 
added to the site configuration options list. 
* Add an option where the author wants to use MathJax v3 instead with `params.setMathjaxToV3` site option. 


=== Changed
* Reduce the font set for Fira Code and replaced it with a single 
https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Fonts/Variable_Fonts_Guide[variable font set]
in https://www.w3.org/TR/WOFF2/[WOFF2] format. 
* Update the default font stack is updated to ensure the look 
will be consistent since the 
https://caniuse.com/#search=variable%20fonts[support for variable fonts] is a bit rough. 
* Remove the `list` key requirement of `projects` and `contact` data file to being a 
list themselves. (I didn't know it's possible for YAML and TOML to contain an equivalent 
of a JSON array.)
* Make MathJax support disabled by default. 
With this effect, `params.enableMathjax` is added into the site config options.


=== Fixed 
* Revise the static search engine index to be used. 
It uses a new separate file named `index.search.json` though it'll require a new 
output format to use it to avoid conflicts with the JSON feeds. 




== [1.3.1] - 2019-09-03 
=== Fixed 
* The list template for the RSS and Atom feeds to be valid. (Just a very 
amateur mistake...)
* JavaScript code for the Disqus comments. (Seems using JavaScript template strings 
is a bit problematic with Hugo's templating system.)



== [1.3.0] - 2019-09-03 
=== Added 
* Support for RSS, Atom, and JSON feeds. 
** `params.feedLimit` parameter has been added to the site configuration for 
controlling the number of output for your feeds. 
** Related files can be found at `index.atom`, `index.json`, `index.rss` at the layout folder. 
** Feeds for list templates can be found at `_default/list.*` as well.

=== Changed
* `index.json` schema has been changed and as a result of supporting JSON feeds, it'll be 
used as the template for the https://jsonfeed.org/[JSON feed]. 
* Tweaked built-in search engine settings (thankfully, it only needs a few things to change). 

=== Fixed
* Disqus comments not showing up. 




== [1.2.1] - 2019-09-02 
=== Added
* `index.json` template that is mainly going to be used as a search engine index. 
* A search function that could be used without Algolia or any similar services 
(though not recommended for large sites).

=== Changed
* Revised the layout to be semantic and SEO-friendly like adding `rel` attributes 
to certain links. 
* Scripts are now concatenated using 
https://gohugo.io/hugo-pipes/bundling/[Hugo asset bundling] to reduce requests 
needed for the whole site. 
* Updated MathJax and Asciidoctor-based stylesheets. 




== [1.2.0] - 2019-09-02 
=== Added
* `index.json` template that is mainly going to be used as a search engine index. 
* A search function that could be used without Algolia or any similar services 
(though not recommended for large sites).

=== Changed
* Revised the layout to be semantic and SEO-friendly like adding `rel` attributes 
to certain links. 
* Scripts are now concatenated using 
https://gohugo.io/hugo-pipes/bundling/[Hugo asset bundling] to reduce requests 
needed for the whole site. 
* Updated MathJax and Asciidoctor-based stylesheets. 




== [1.1.1] - 2019-08-31 
=== Changed
* Corrected the SCSS configuration by migrating the default config to 
`default.scss` at SCSS assets folder (link:assets/scss[`assets/scss`]). 
* Revised the layouts. 




== [1.1.0] - 2019-08-30  
=== Added
* This changelog. ;p
* https://prismjs.com/plugins/keep-markup/[Keep Markup plugin] to 
https://prismjs.com/[PrismJS] to fix the Asciidoctor callouts and style them 
appropriately.
* Style to callouts for improved reader experience. 
* https://highlightjs.org/[`highlightjs`] is added as an additional syntax 
highlighter. 
* `syntaxHighlighter` site config option as setting the syntax highlighter. 
This time `highlightjs` is the default. 
* Sample articles made in both Asciidoctor and Markdown. (Demo will be out soon.)

=== Changed
* `syntaxHighlighting` name to `enableSyntaxHighlighting` for consistent option 
naming in the site configurations.
* Refactored some layouts.
* Moved the CSS files into their appropriate locations at `asset/css`. 
