= Changelog

All notable changes to this project will be documented in this file.

The format is based on https://keepachangelog.com/en/1.0.0/[Keep a Changelog],
and this project adheres to https://semver.org/spec/v2.0.0.html[Semantic Versioning].

== [Unreleased]
=== Removed

* Remove the web feeds feature in favor of link:https://github.com/foo-dogsquared/hugo-web-feeds/[my web feeds theme component].
While this removes a part of the value of the theme now that the feature is modularized but it is easier to set the web feeds by tenfold.
Plus, it removes the burden of maintaining this feature only for this theme so that's always nice.

* Remove `listSiteSectionsOnHome` parameter.
(It's kind of useless now that I think about it.)

* Remove the `img` key from contacts schema as it fully relies on Simple Icons set now.
It's there for the sake of consistency though I acknowledge not all icons can be fitted into the set.


=== Changed

* Change the archives as a layout instead of a type — i.e., `layouts/_default/archives.html` instead of `layouts/archives/`.
It now requires the `layout` key in the frontmatter instead of the `type` key.

* Change the included libraries to be linked from link:https://cdnjs.com/[cdnjs] instead of vendoring them.
Despite the significance of CDNs are dwindling on personal websites in favor of client-side security features such as link:https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity[subresource integrity] and link:https://developer.mozilla.org/en-US/docs/Web/Privacy#fingerprinting[fingerprinting], a lot of the libraries are popular and it is best to make it easier for the users.

* Update the Simple Icons integration by Hugo modules instead of static downloading of their assets (which is always incomplete, my mistake :>).
This, in turn, now requires the theme to have the Go runtime to be installed in order to install it.




== [2.3.0] - 2019-10-21
=== Removed

* Remove the portfolio layout.
I find it to be a to add a portfolio when you can just write it in a content file.
It is also more suitable to be an extension to the theme than a built-in feature.

=== Changed

* Update the stylesheets.
* Change the location of the output formats.




== [2.2.2] - 2019-09-24
=== Changed
* Update the pagination layout
* Update the stylesheets

=== Fixed
* Revert the math support parameter name to `params.enableMathjax` (that was a leftover, sorry)



== [2.2.1] - 2019-09-15
=== Changed
* Revise the MathJax script loading mechanism.
* Polish the stylesheets and layouts.




== [2.2.0] - 2019-09-12
=== Removed
* Remove the syntax highlighter choices and make PrismJS as the primary syntax highlighter.
The user can easily include their own library, anyways.
Thus, `params.syntaxHighlighter` will be removed from the site config options.
* Remove the choice of using MathJax v2.
Thus, `params.setMathjaxToV2` will be removed from the site config options.
* Remove the choice of using local MathJax.
The script is too big and composes overwhelmingly majority of the repo size.
Thus, `params.useLocalMathjax` is removed.
* Remove `params.enableCompactListMode` and make it as the default list view instead.
* Remove `params.enableContentReaderMode` and make it as the default content view instead.
* Remove `params.contentIsStyled`.




== [2.1.0] - 2019-09-11
=== Added
* Utilize https://gohugo.io/functions/where/#mainsections[`params.mainSections`]
for the homepage posts list.

=== Changed
* **BREAKING CHANGE**: The `libraries` data file now requires a `type` key for supporting custom CSS stylesheets.
Possible values for this key includes only `js` and `css`.
* Change the implementation of `useLinkIcons` that relies from a static SVG spritesheet to
the user's custom definition with the `img` key.
That said, an additional key is added for the `contacts` item which is the `img` key.

=== Fixed
* Label with appropriate markup of the buttons included.
* Make all scripts to be deferred (except for the custom libraries where they have
to be explicitly defined to be deferred).
* Fix layout stylesheets and the metadata in the `<head>`.
* Refactor the code for the layouts.




== [2.0.1] - 2019-09-10
=== Changed
* Change the execution of the MathJax (through CDN) script to be deferred instead of
asynchronously executed to increase perceived page performance.

=== Fixed
* Fix the incorrect values inserted into the `<head>`. (Big mistake to use `partialCached`
since it dynamically changes. Whoops.)



== [2.0.0] - 2019-09-10
=== Added
* https://gohugo.io/content-management/multilingual/[Multilingual mode] support.
Thus, the `i18n` folder is now added.
For now, the translation is only available for English (US) and Tagalog.
If you know some language that is not listed in the folder, feel free to contribute translating to other languages.
* Add asset fingerprinting to the theme assets.
* Add user-configured libraries list to add to your Hugo site.
* Add quick taxonomy search list.
The feature was inspired from https://www.ii.com/[this site].
* Add a CDN-less MathJax usage option as `params.useLocalMathjax`.
(Only works for MathJax v3.)
* Add custom messages for the 404 page.
Thus, the following site custom parameters has been added:
** `params.notFoundHeader`
** `params.notFoundLinkMessage`
** `params.notFoundMessage`
* Add a custom message option for the search widget label by `params.searchLabel`.
* Add content headers (similar to
https://en.wikibooks.org/wiki/LaTeX/Counters[LaTeX counters]) with the
`params.useContentCounters` option.
* Add a reader mode for your content with `params.enableContentReaderMode`.
* Add a compact list mode for the homepage post list with `params.enableCompactListMode`.
* Add a "Back to top" button on the footer with `params.enableBackToTopLink`.
* Add JSON+LD schema.
It is disabled by default so you have to manually switch the `params.enableJsonLdSchema` first.
* Add a image zoom feature (using
https://github.com/francoischalifour/medium-zoom[medium-zoom library]) that can be
switched with `params.enableContentImageZoom`.
You can also set the background color with `params.setContentImageZoomBackground`.

=== Removed
* Remove the custom fonts and let the user customize their own.
This also improves the performance of the base theme.

=== Changed
* **IMPORTANT**: Rename the theme from "Terminal Plus-Minus" to "Arch Terminal" along
with a slight rebrand.
* **IMPORTANT**: Content pagination is now disabled by default.
In effect, an additional site config option `params.enableContentPagination` has
been added.
* **BREAKING CHANGE**: Invert the setting to hide the posts instead of showing posts
manually.
Thus, `params.showPostsOnHome` have been replaced with `params.hidePostsOnHome`.
* **BREAKING CHANGE**: Update the layout code for the
https://github.com/gohugoio/hugo/releases/tag/v0.58.0[breaking changes at Hugo v0.58.0].
__Thus, the theme now requires Hugo v0.58.0.__
* **BREAKING CHANGE**: Change `params.enableSyntaxHighlighting` to
`params.enableLazySyntaxHighlighting`.
* **BREAKING CHANGE**: Remove `params.setMathjaxToV3` to be replaced with
`params.setMathjaxToV2` since the theme will now use MathJax v3 by default.
* Revise MathJax support (again) with the v2 replaced to v3 as the
default MathJax version since MathJax v3 got the official production release.
* Update the stylesheet to consider consistent and pleasant typography.
One of the biggest change is the consideration of
https://zellwk.com/blog/why-vertical-rhythms/[vertical rhythms] and the absence of
the custom styles.
* Twitter cards and OpenGraph schema are now disabled by default and has to be
enabled with `params.enableTwitterCard` and `params.enableOpenGraphSchema` respectively.

=== Fixed
* Update the SCSS load order to make the automatic second theming work.
(I forgot that SCSS variables are imperative, not declarative.)
* Make the external scripts to run asynchronously to prevent DOM blocking and
improve the performance of the site.




== [1.4.0] - 2019-09-05
=== Added
* Add a theme toggle switch (or dark mode toggle switch or whatever).
Thus, additional variables in the default stylesheet config has been added.
Please take a look at the link:../assets/scss/default.scss[default config] to
see the added variables.
* The toggle switch is disabled by default so the `params.enableThemeToggle` is
added to the site configuration options list.
* Add an option where the author wants to use MathJax v3 instead with `params.setMathjaxToV3` site option.


=== Changed
* Reduce the font set for Fira Code and replaced it with a single
https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Fonts/Variable_Fonts_Guide[variable font set]
in https://www.w3.org/TR/WOFF2/[WOFF2] format.
* Update the default font stack is updated to ensure the look
will be consistent since the
https://caniuse.com/#search=variable%20fonts[support for variable fonts] is a bit rough.
* Remove the `list` key requirement of `projects` and `contact` data file to being a
list themselves. (I didn't know it's possible for YAML and TOML to contain an equivalent
of a JSON array.)
* Make MathJax support disabled by default.
With this effect, `params.enableMathjax` is added into the site config options.


=== Fixed
* Revise the static search engine index to be used.
It uses a new separate file named `index.search.json` though it'll require a new
output format to use it to avoid conflicts with the JSON feeds.




== [1.3.1] - 2019-09-03
=== Fixed
* The list template for the RSS and Atom feeds to be valid. (Just a very
amateur mistake...)
* JavaScript code for the Disqus comments. (Seems using JavaScript template strings
is a bit problematic with Hugo's templating system.)



== [1.3.0] - 2019-09-03
=== Added
* Support for RSS, Atom, and JSON feeds.
** `params.feedLimit` parameter has been added to the site configuration for
controlling the number of output for your feeds.
** Related files can be found at `index.atom`, `index.json`, `index.rss` at the layout folder.
** Feeds for list templates can be found at `_default/list.*` as well.

=== Changed
* `index.json` schema has been changed and as a result of supporting JSON feeds, it'll be
used as the template for the https://jsonfeed.org/[JSON feed].
* Tweaked built-in search engine settings (thankfully, it only needs a few things to change).

=== Fixed
* Disqus comments not showing up.




== [1.2.1] - 2019-09-02
=== Added
* `index.json` template that is mainly going to be used as a search engine index.
* A search function that could be used without Algolia or any similar services
(though not recommended for large sites).

=== Changed
* Revised the layout to be semantic and SEO-friendly like adding `rel` attributes
to certain links.
* Scripts are now concatenated using
https://gohugo.io/hugo-pipes/bundling/[Hugo asset bundling] to reduce requests
needed for the whole site.
* Updated MathJax and Asciidoctor-based stylesheets.




== [1.2.0] - 2019-09-02
=== Added
* `index.json` template that is mainly going to be used as a search engine index.
* A search function that could be used without Algolia or any similar services
(though not recommended for large sites).

=== Changed
* Revised the layout to be semantic and SEO-friendly like adding `rel` attributes
to certain links.
* Scripts are now concatenated using
https://gohugo.io/hugo-pipes/bundling/[Hugo asset bundling] to reduce requests
needed for the whole site.
* Updated MathJax and Asciidoctor-based stylesheets.




== [1.1.1] - 2019-08-31
=== Changed
* Corrected the SCSS configuration by migrating the default config to
`default.scss` at SCSS assets folder (link:assets/scss[`assets/scss`]).
* Revised the layouts.




== [1.1.0] - 2019-08-30
=== Added
* This changelog. ;p
* https://prismjs.com/plugins/keep-markup/[Keep Markup plugin] to
https://prismjs.com/[PrismJS] to fix the Asciidoctor callouts and style them
appropriately.
* Style to callouts for improved reader experience.
* https://highlightjs.org/[`highlightjs`] is added as an additional syntax
highlighter.
* `syntaxHighlighter` site config option as setting the syntax highlighter.
This time `highlightjs` is the default.
* Sample articles made in both Asciidoctor and Markdown. (Demo will be out soon.)

=== Changed
* `syntaxHighlighting` name to `enableSyntaxHighlighting` for consistent option
naming in the site configurations.
* Refactored some layouts.
* Moved the CSS files into their appropriate locations at `asset/css`.
