= Changelog

All notable changes to this project will be documented in this file.

The format is based on https://keepachangelog.com/en/1.0.0/[Keep a Changelog],
and this project adheres to https://semver.org/spec/v2.0.0.html[Semantic Versioning].

== [Unreleased] 



== [1.3.0] - 2019-09-03 
=== Added 
* Support for RSS, Atom, and JSON feeds. 
** `params.feedLimit` parameter has been added to the site configuration for 
controlling the number of output for your feeds. 
** Related files can be found at `index.atom`, `index.json`, `index.rss` at the layout folder. 
** Feeds for list templates can be found at `_default/list.*` as well.

=== Changed
* `index.json` schema has been changed and as a result of supporting JSON feeds, it'll be 
used as the template for the https://jsonfeed.org/[JSON feed]. 
* Tweaked built-in search engine settings (thankfully, it only needs a few things to change). 

=== Fixed
* Disqus comments not showing up. 




== [1.2.0] - 2019-09-02 
=== Added
* `index.json` template that is mainly going to be used as a search engine index. 
* A search function that could be used without Algolia or any similar services 
(though not recommended for large sites).

=== Changed
* Revised the layout to be semantic and SEO-friendly like adding `rel` attributes 
to certain links. 
* Scripts are now concatenated using 
https://gohugo.io/hugo-pipes/bundling/[Hugo asset bundling] to reduce requests 
needed for the whole site. 
* Updated MathJax and Asciidoctor-based stylesheets. 




== [1.1.1] - 2019-08-31 
=== Changed
* Corrected the SCSS configuration by migrating the default config to 
`default.scss` at SCSS assets folder (link:assets/scss[`assets/scss`]). 
* Revised the layouts. 




== [1.1.0] - 2019-08-30  
=== Added
* This changelog. ;p
* https://prismjs.com/plugins/keep-markup/[Keep Markup plugin] to 
https://prismjs.com/[PrismJS] to fix the Asciidoctor callouts and style them 
appropriately.
* Style to callouts for improved reader experience. 
* https://highlightjs.org/[`highlightjs`] is added as an additional syntax 
highlighter. 
* `syntaxHighlighter` site config option as setting the syntax highlighter. 
This time `highlightjs` is the default. 
* Sample articles made in both Asciidoctor and Markdown. (Demo will be out soon.)

=== Changed
* `syntaxHighlighting` name to `enableSyntaxHighlighting` for consistent option 
naming in the site configurations.
* Refactored some layouts.
* Moved the CSS files into their appropriate locations at `asset/css`. 
